pattern: "GBRG"
bit_width: 10
img_width: 720
img_height: 720

modules:
  blc_0:
    module_type: blc
    black_level: 64

  wb_0:
    module_type: wb
    white_balance: [1.35, 1.0, 1.0, 1.4]
    # white_balance: [1.4, 1.0, 1.0, 1.6]  # vessel

  lsc_0:
    module_type: lsc
    gain_path: src/modules/lsc_gains/oh0fa10.bin
    gain_pattern: GBRG
    luma_shading_ratio: 0.25

  ccm_0:
    module_type: ccm
    color_correction_matrix:
      [1.252, -0.663, 0.411, -0.298, 1.418, -0.120, -0.134, -0.663, 1.797]

  gamma_0:
    module_type: gamma
    type: "rec709"

  demosaic_0:
    module_type: demosaic

  debayer_0:
    module_type: debayer

  ltm_0:
    module_type: ltm
    gray_max_ratio: 0.5
    kernel: 80
    stride: 40
    gama: 709
    frac: 3
    local_factor: 0.875
    clahe_thresh: 0.08966 
    factor_thresh: 2.75

  rgb2yuv_0:
    module_type: color_space_conversion
    type: rgb2yuv

  yuv2rgb_0:
    module_type: color_space_conversion
    type: yuv2rgb

  ai_denoise_0:
    module_type: ai_denoise
    black_level: 64
    network_range: 256
    # model: unet
    # model_path: /share/shishi/lyxbigmodelpmrid_epoch8000.pth
    model: pmrid
    model_path: /share/mingyue/model_trained/0705_16_tune/train_pmridpmrid_epoch665.pth

  bf_0:
    module_type: bilateral_filter
    kernel_size: 7
    sigmas: 1.5
    sigmar: 30

  log_0:
    module_type: LoG
    sigma: [1, 2, 5]
    kernel_size: 15
    alpha: [2, 10, 6]

  vessel_enhancement_0:
    module_type: vessel_enhancement
    gauss_sigma: 25
    rgb_coef: [1, 1, 1]
    detail_coef: 1

  green_equil_0:
    module_type: green_equil
    thresh: 1

  rgb2hsv_0:
    module_type: color_space_conversion
    type: rgb2hsv

  hsv2rgb_0:
    module_type: color_space_conversion
    type: hsv2rgb

  dct_0:
    module_type: raw_denoise
    ak: [0.2094, 0.2074, 0.2106, 0.2114]
    bk: [0.442, 0.571, 0.523, 0.354]
    bb: [1.42, 1.59, 1.60, 1.53]
    gain: 1.5
    stride: 1
    thresh: [1, 1, 1, 1]

  median_filter_0:
    module_type: median_filter
    axis: [1, 2]
    kernel: 7

  dpc_0:
    module_type: dpc
    dark_pixel_median_thresh: 12
    dark_pixel_median_ratio: 0.58
    white_pixel_subsmallest_thresh: 32

  local_color_enhancement_0:
    module_type: local_color_enhancement
    kernel: 120
    stride: 60
    hue_min: 0.25
    hue_max: 0.78
    value_min: 64
    value_max: 1024
    ds_min: 0.25
    ds_max: 3
    alpha: 2.2
    smooth_ratio_min: 0.2
    smooth_ratio_max: 0.7

  hsv_adjust_0:
    module_type: hsv_adjust
    hue_adjust_value: {'rr': 15, 'rg': 15, 'gg': 15, 'gb': 15, 'bb': 15, 'br': 15}
    saturation_adjust_value: {'rr': 15, 'rg': 15, 'gg': 15, 'gb': 15, 'bb': 15, 'br': 15}
    value_adjust_value: {'rr': 15, 'rg': 15, 'gg': 15, 'gb': 15, 'bb': 15, 'br': 15}

  undistortion_0:
    module_type: undistortion
    mtx_f: [432.5,433.875]
    mtx_c: [359.8125,351.875,0.0]
    dist_k: [-0.133544921875,-0.082763671875,0.06005859375]
    dist_p: [-0.000732421875,-0.00048828125]
    undistort_channel: 1
    undistort_depth: 10

runtime:
  data_type: "float32"
  device: "cuda:1"
  modules: [
      blc_0,
      # dpc_0,
      dct_0,
      wb_0,
      lsc_0,
      green_equil_0,
      undistortion_0,
      # ltm_0,
      demosaic_0,
      # debayer_0,
      # ccm_0,
      gamma_0,
      rgb2yuv_0,
      median_filter_0,
      bf_0,
      # log_0,
      yuv2rgb_0,
      # vessel_enhancement_0,
      # hsv_adjust_0,
      # rgb2hsv_0,
      # hsv2rgb_0
    ]
