pattern: "GRBG"
bit_width: 10
img_width: 1280
img_height: 720

modules:
  blc_0:
    module_type: blc
    black_level: 16

  wb_0:
    module_type: wb
    white_balance: [2., 1.0, 1.0, 1.675]

  ccm_0:
    module_type: ccm
    color_correction_matrix:
      [
        1.3562,
        -0.4014,
        0.0452,
        -0.2957,
        1.5850,
        -0.2893,
        -0.0667,
        -0.5667,
        1.6334,
      ]

  gamma_0:
    module_type: gamma
    type: "rec709"

  demosaic_0:
    module_type: demosaic

  ltm_0:
    module_type: ltm
    gray_max_ratio: 0.5
    kernel: 80
    stride: 40
    gama: 709
    frac: 3
    local_factor: 0.875
    clahe_thresh: 0.08966 
    factor_thresh: 2.75

  rgb2yuv_0:
    module_type: color_space_conversion
    type: rgb2yuv

  yuv2rgb_0:
    module_type: color_space_conversion
    type: yuv2rgb

  pmrid_0:
    module_type: ai_denoise
    black_level: 64
    network_range: 256
    model_path: /share/mingyue/model_trained/0705_16_tune/train_pmridpmrid_epoch665.pth

  bf_0:
    module_type: bilateral_filter
    kernel_size: 7
    sigmas: 1.5
    sigmar: 200

  log_0:
    module_type: LoG
    sigma: [1, 2, 5]
    kernel_size: 15
    alpha: [2, 6, 3]

  green_equil_0:
    module_type: green_equil
    thresh: 1

  undistortion_0:
    module_type: undistortion
    mtx_f: [711.3125,715.3125]
    mtx_c: [621.375,352.0,0.0]
    dist_k: [-0.218017578125,-0.019287109375,0.037353515625]
    dist_p: [0.0009765625,0.003173828125]
    undistort_channel: 1
    undistort_depth: 10

runtime:
  data_type: "float32"
  device: "cuda"
  modules:
    [
      blc_0,
      wb_0,
      green_equil_0,
      undistortion_0,
      # ltm_0,
      demosaic_0,
      ccm_0,
      gamma_0,
      rgb2yuv_0,
      bf_0,
      log_0,
      yuv2rgb_0,
    ]
